$(document).ready(function() {
	$("#home").hide();
	$("#upload").hide();
	$("#login").hide();
	$("#display").hide();
	$("#searchFile").hide();
	$("#nUser").hide();
	$("#rPage").hide();
	$("#vFiles").hide();
	$("#uProfile").hide();
	$("#viewUsers").hide();
	$("#filesViewer").hide();
	var home = $("#home").html();
	var upload = $("#upload").html();
	var login = $("#login").html();
	var register = $("#rPage").html();
	var vFiles = $("#vFiles").html();
	var uProfile = $("#uProfile").html();
	var viewUsers = $("#viewUsers").html();
	var filesViewer = $("#filesViewer").html();
	$("#main").html(home);
	$("#lClick").click(function() {
		$("#home").hide();
		$("#upload").hide();
		$("#viewUsers").hide();
		$("#display").hide();
		$("#filesViewer").hide();
		$("#searchFile").hide();
		$("#nUser").show();
		$("#rPage").hide();
		$("#vFiles").hide();
		$("#uProfile").hide();
		$("#main").html(login);
	});
	$("#viewFiles").click(function() {
		$("#home").hide();
		$("#upload").hide();
		$("#display").hide();
		$("#filesViewer").hide();
		$("#searchFile").hide();
		$("#nUser").hide();
		$("#rPage").hide();
		$("#vFiles").hide();
		$("#uProfile").hide();
		$("#main").html(filesViewer);
	});
	$("#hClick").click(function() {
		$("#upload").hide();
		$("#login").hide();
		$("#searchFile").hide();
		$("#display").hide();
		$("#filesViewer").hide();
		$("#nUser").hide();
		$("#viewUsers").hide();
		$("#rPage").hide();
		$("#vFiles").hide();
		$("#uProfile").hide();
		$("#main").html(home);
	});
	$("#uClick").click(function() {
		$("#home").hide();
		$("#login").hide();
		$("#display").hide();
		$("#viewUsers").hide();
		$("#searchFile").show();
		$("#filesViewer").hide();
		$("#nUser").hide();
		$("#rPage").hide();
		$("#vFiles").hide();
		$("#uProfile").hide();
		$("#main").html(upload);
	});
	$("#nUser").click(function() {
		$("#home").hide();
		$("#login").hide();
		$("#display").hide();
		$("#searchFile").hide();
		$("#filesViewer").hide();
		$("#viewUsers").hide();
		$("#nUser").hide();
		$("#vFiles").hide();
		$("#uProfile").hide();
		$("#main").html(register);
	});
	$("#vFile").click(function() {
		$("#home").hide();
		$("#login").hide();
		$("#viewUsers").hide();
		$("#display").hide();
		$("#filesViewer").hide();
		$("#searchFile").hide();
		$("#nUser").hide();
		$("#main").html(vFiles);
	});
	$("#profile").click(function() {
		$("#home").hide();
		$("#login").hide();
		$("#filesViewer").hide();
		$("#viewUsers").hide();
		$("#display").hide();
		$("#searchFile").hide();
		$("#nUser").hide();
		$("#main").html(uProfile);
	});
});
